# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: "smail"
    replace: "davelai@kkcompany.com"

  - trigger: "sreject"
    replace: "curl http://elasticsearch.videopass:9200/_cat/thread_pool?v"

  - trigger: "sstresshost"
    replace: "https://api-videopass.videopass.kkvqa.com"

  - trigger: "ssgearmanjobs"
    replace: "gearadmin -h gearman-1.videopass --status | sort -n | column -t"

  - trigger: "ssgearmanlogs"
    replace: "/var/log/gearman-manager.log"

  - trigger: "ssp"
    replace: " (sprint ticket: )"

  - trigger: "sstemp"
    replace: "VP-24461"

  - trigger: "ssecret"
    replace: "/kkcorp/kksecret"

  - trigger: "svp"
    replace: "VideoPass"

  - trigger: "sgd"
    replace: ":+1:"

  - trigger: "vsgd"
    replace: ":thankyou: :感恩: :thank-you: :thank-1::worship7::worship_hyper::worship6::worship5::worship3::worshippp:"
