# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: "smail"
    replace: "davelai@kkcompany.com"

  - trigger: "sreject"
    replace: "curl http://elasticsearch.videopass:9200/_cat/thread_pool?v"

  - trigger: "sstresshost"
    replace: "https://api-videopass.videopass.kkvqa.com"

  - trigger: "ssp"
    replace: " (sprint ticket: )"

  - trigger: "sconfig"
    replace: "/kkcorp/config-videopass"

  - trigger: "ssecret"
    replace: "/kkcorp/kksecret"

  - trigger: "svp"
    replace: "VideoPass"

  - trigger: "sgd"
    replace: ":+1"