import subprocess
from datetime import datetime, timedelta

# 定義時間範圍和交易對
# timeframes = ["1m", "5m", "15m"]
# timeframes = ["1m"]
# timeframes = ["15m"]
# timeframes = ["5m"]
timeframes = ["3m"]
# full
# pairs = ["BTC/USDT:USDT","ETH/USDT:USDT","SOL/USDT:USDT","TRUMP/USDT:USDT","VINE/USDT:USDT","JUP/USDT:USDT","XRP/USDT:USDT","DOGE/USDT:USDT","SPELL/USDT:USDT","1000PEPE/USDT:USDT","SUI/USDT:USDT","OM/USDT:USDT","FARTCOIN/USDT:USDT","ENA/USDT:USDT","LINK/USDT:USDT","BNB/USDT:USDT","ADA/USDT:USDT","LTC/USDT:USDT","PNUT/USDT:USDT","SKL/USDT:USDT","WIF/USDT:USDT","RUNE/USDT:USDT","TAO/USDT:USDT","PENGU/USDT:USDT","ONDO/USDT:USDT","MELANIA/USDT:USDT","AVAX/USDT:USDT","WLD/USDT:USDT","HBAR/USDT:USDT","AAVE/USDT:USDT","NEIRO/USDT:USDT","LDO/USDT:USDT","ACT/USDT:USDT","1000BONK/USDT:USDT","ACH/USDT:USDT","AIXBT/USDT:USDT","MOODENG/USDT:USDT","DOT/USDT:USDT","FIL/USDT:USDT","1000SHIB/USDT:USDT","AI16Z/USDT:USDT","XLM/USDT:USDT","SWARMS/USDT:USDT","ANIME/USDT:USDT","USUAL/USDT:USDT","APT/USDT:USDT","OP/USDT:USDT","NEAR/USDT:USDT","TRX/USDT:USDT","POPCAT/USDT:USDT","MOVE/USDT:USDT","CRV/USDT:USDT","UNI/USDT:USDT","TIA/USDT:USDT","GRIFFAIN/USDT:USDT","ARB/USDT:USDT","ETC/USDT:USDT","VTHO/USDT:USDT","HIVE/USDT:USDT","FET/USDT:USDT","VIRTUAL/USDT:USDT","ORDI/USDT:USDT","ARC/USDT:USDT","GALA/USDT:USDT","GOAT/USDT:USDT","ALGO/USDT:USDT","UXLINK/USDT:USDT","BCH/USDT:USDT","INJ/USDT:USDT","BAN/USDT:USDT","EIGEN/USDT:USDT","EOS/USDT:USDT","ATOM/USDT:USDT","BOME/USDT:USDT","ZEN/USDT:USDT","JTO/USDT:USDT","SEI/USDT:USDT","SOLV/USDT:USDT","ETHFI/USDT:USDT","1000SATS/USDT:USDT","APE/USDT:USDT","BIO/USDT:USDT","RAYSOL/USDT:USDT","PIPPIN/USDT:USDT","GMT/USDT:USDT","ALCH/USDT:USDT","PENDLE/USDT:USDT","TURBO/USDT:USDT","AGLD/USDT:USDT","SAND/USDT:USDT","1000FLOKI/USDT:USDT","RENDER/USDT:USDT","SPX/USDT:USDT","PEOPLE/USDT:USDT","DEGEN/USDT:USDT","MORPHO/USDT:USDT","IO/USDT:USDT","ENS/USDT:USDT","NOT/USDT:USDT","CFX/USDT:USDT","AVAAI/USDT:USDT","CHILLGUY/USDT:USDT","DYDX/USDT:USDT","ARKM/USDT:USDT","BEL/USDT:USDT","TON/USDT:USDT","JASMY/USDT:USDT","ZEREBRO/USDT:USDT","VANA/USDT:USDT","1MBABYDOGE/USDT:USDT","RSR/USDT:USDT","ICP/USDT:USDT","VET/USDT:USDT","DOGS/USDT:USDT","CGPT/USDT:USDT","STEEM/USDT:USDT","STX/USDT:USDT","COOKIE/USDT:USDT","SAGA/USDT:USDT","COW/USDT:USDT","DF/USDT:USDT","GRT/USDT:USDT","PYTH/USDT:USDT","IOTA/USDT:USDT","THE/USDT:USDT","D/USDT:USDT","1000CAT/USDT:USDT","SUSHI/USDT:USDT","ZRO/USDT:USDT","POL/USDT:USDT","SONIC/USDT:USDT","1000000MOG/USDT:USDT","ME/USDT:USDT","MKR/USDT:USDT","OGN/USDT:USDT","AR/USDT:USDT","ARPA/USDT:USDT","QNT/USDT:USDT","ONT/USDT:USDT","THETA/USDT:USDT","STRK/USDT:USDT","KMNO/USDT:USDT","MEME/USDT:USDT","TRB/USDT:USDT","S/USDT:USDT","XTZ/USDT:USDT","GRASS/USDT:USDT","MANA/USDT:USDT","SWELL/USDT:USDT","OMNI/USDT:USDT","AI/USDT:USDT","CHZ/USDT:USDT","FIDA/USDT:USDT","PHA/USDT:USDT","ZK/USDT:USDT","BEAMX/USDT:USDT","1000LUNC/USDT:USDT","COMP/USDT:USDT","BRETT/USDT:USDT","BIGTIME/USDT:USDT","NEO/USDT:USDT","AERO/USDT:USDT","DEXE/USDT:USDT","DRIFT/USDT:USDT","AXS/USDT:USDT","GAS/USDT:USDT","ZRX/USDT:USDT","XMR/USDT:USDT","ORCA/USDT:USDT","1000RATS/USDT:USDT","CAKE/USDT:USDT","SSV/USDT:USDT","XAI/USDT:USDT","HIPPO/USDT:USDT","FLOW/USDT:USDT","W/USDT:USDT","STG/USDT:USDT","LPT/USDT:USDT","XVG/USDT:USDT","NEIROETH/USDT:USDT","AEVO/USDT:USDT","SCR/USDT:USDT","SXP/USDT:USDT","MEW/USDT:USDT","MANTA/USDT:USDT","ONE/USDT:USDT","BAT/USDT:USDT","ALT/USDT:USDT","BLUR/USDT:USDT","MOCA/USDT:USDT","TROY/USDT:USDT","EGLD/USDT:USDT","LUMIA/USDT:USDT","IMX/USDT:USDT","KDA/USDT:USDT","1INCH/USDT:USDT","TRU/USDT:USDT","CETUS/USDT:USDT","VANRY/USDT:USDT","SNX/USDT:USDT","MASK/USDT:USDT","ROSE/USDT:USDT","PIXEL/USDT:USDT","1000CHEEMS/USDT:USDT","SUPER/USDT:USDT","PONKE/USDT:USDT","POLYX/USDT:USDT","KSM/USDT:USDT","LUNA2/USDT:USDT","CHR/USDT:USDT","TNSR/USDT:USDT","BAND/USDT:USDT","KAS/USDT:USDT","KAVA/USDT:USDT","CATI/USDT:USDT","SAFE/USDT:USDT","AXL/USDT:USDT","BTCDOM/USDT:USDT","BANANA/USDT:USDT","HOT/USDT:USDT","VELODROME/USDT:USDT","YFI/USDT:USDT","ATA/USDT:USDT","BB/USDT:USDT","MTL/USDT:USDT","ZIL/USDT:USDT","CELO/USDT:USDT","PORTAL/USDT:USDT","POWR/USDT:USDT","COS/USDT:USDT","MINA/USDT:USDT","LQTY/USDT:USDT","DYM/USDT:USDT","HIFI/USDT:USDT","1000X/USDT:USDT","STMX/USDT:USDT","BAKE/USDT:USDT","AERGO/USDT:USDT","G/USDT:USDT","ACX/USDT:USDT","YGG/USDT:USDT","REZ/USDT:USDT","JOE/USDT:USDT","ICX/USDT:USDT","XVS/USDT:USDT","KAIA/USDT:USDT","IOTX/USDT:USDT","AVA/USDT:USDT","GTC/USDT:USDT","ARK/USDT:USDT","KNC/USDT:USDT","CKB/USDT:USDT","ALICE/USDT:USDT","HMSTR/USDT:USDT","ENJ/USDT:USDT","HOOK/USDT:USDT","COTI/USDT:USDT","IOST/USDT:USDT","MYRO/USDT:USDT","C98/USDT:USDT","STORJ/USDT:USDT","1000WHY/USDT:USDT","LIT/USDT:USDT","GMX/USDT:USDT","MAGIC/USDT:USDT","DASH/USDT:USDT","ZEC/USDT:USDT","NFP/USDT:USDT","METIS/USDT:USDT","FLM/USDT:USDT","BICO/USDT:USDT","SANTOS/USDT:USDT","API3/USDT:USDT","MBOX/USDT:USDT","ALPHA/USDT:USDT","RONIN/USDT:USDT","LISTA/USDT:USDT","KOMA/USDT:USDT","HIGH/USDT:USDT","LRC/USDT:USDT","TWT/USDT:USDT","LINA/USDT:USDT","FIO/USDT:USDT","NKN/USDT:USDT","ASTR/USDT:USDT","BADGER/USDT:USDT","CYBER/USDT:USDT","ONG/USDT:USDT","ID/USDT:USDT","ANKR/USDT:USDT","WOO/USDT:USDT","WAXP/USDT:USDT","ZETA/USDT:USDT","CELR/USDT:USDT","CTSI/USDT:USDT","BNX/USDT:USDT","QTUM/USDT:USDT","ACE/USDT:USDT","ILV/USDT:USDT","TLM/USDT:USDT","VOXEL/USDT:USDT","DUSK/USDT:USDT","TOKEN/USDT:USDT","FXS/USDT:USDT","GLM/USDT:USDT","RLC/USDT:USDT","MOVR/USDT:USDT","RDNT/USDT:USDT","SLERF/USDT:USDT","PHB/USDT:USDT","DENT/USDT:USDT","UMA/USDT:USDT","LEVER/USDT:USDT","EDU/USDT:USDT","AUCTION/USDT:USDT","SYN/USDT:USDT","DODOX/USDT:USDT","LSK/USDT:USDT","BSV/USDT:USDT","PROM/USDT:USDT","SFP/USDT:USDT","T/USDT:USDT","1000XEC/USDT:USDT","RARE/USDT:USDT","VIDT/USDT:USDT","MAV/USDT:USDT","AKT/USDT:USDT","SCRT/USDT:USDT","OXT/USDT:USDT","USTC/USDT:USDT","NMR/USDT:USDT","RVN/USDT:USDT","FLUX/USDT:USDT","ETHW/USDT:USDT","BAL/USDT:USDT","HFT/USDT:USDT","PERP/USDT:USDT","DIA/USDT:USDT","RPL/USDT:USDT","SUN/USDT:USDT","COMBO/USDT:USDT","SYS/USDT:USDT","BNT/USDT:USDT","AMB/USDT:USDT","NTRN/USDT:USDT","LOKA/USDT:USDT","REI/USDT:USDT","USDC/USDT:USDT","BSW/USDT:USDT","CHESS/USDT:USDT","ALPACA/USDT:USDT","NULS/USDT:USDT","DEFI/USDT:USDT","RIF/USDT:USDT","DEGO/USDT:USDT","GHST/USDT:USDT","QUICK/USDT:USDT","OMG/USDT:USDT"]
# pairs = ["BTC/USDT:USDT","ETH/USDT:USDT"]
pairs = ["\".*/USDT:USDT\""]
fetchHours = 8

# 1749359740-1749446140 已跑 1m
# 24h - 1m 跑 15 分鐘
# 5m 跑 8 分鐘
# 15m 跑 6 分鐘

start_time = datetime.now() - timedelta(hours=fetchHours)
start_time_timestamp = int(start_time.timestamp())
end_time = datetime.now()
end_time_timestamp = int(end_time.timestamp())


timerange = f"{start_time_timestamp}-{end_time_timestamp}"
# timerange = "1738330407-1738341207"
# timerange = "1737982767-1739710767"
# 載過的紀錄: 1737982767-1739710767 / 5m

parisString = " ".join(pairs)
# parisString = f"\".*/USDT:USDT\""

# timerange = f"{start_time_timestamp}-{end_time_timestamp}"
# print(f"timerange: --timerange='{timerange}'")

for timeFrame in timeframes:
    # 設定命令
    # command = f"freqtrade download-data --pairs {pair} --exchange binance --days 5 -t {timeFrame}"

    # split with whitespace
    # command = f"freqtrade download-data --pairs {parisString} --exchange binance --timerange='{timerange}' -t {timeFrame} --trading-mode futures"
    # command = f"freqtrade download-data --pairs {parisString} --exchange binance --timerange='{start_time_timestamp}-{end_time_timestamp}' -t {timeFrame} --trading-mode futures"
    command = f"freqtrade download-data --pairs \".*/USDT:USDT\" --exchange binance --timerange='{start_time_timestamp}-{end_time_timestamp}' -t {timeFrame} --trading-mode futures"

    # 執行命令並捕捉輸出
    print(f"Running command: {command}")
    result = subprocess.run(command, shell=True, capture_output=True, text=True)

    # 打印命令的標準輸出和錯誤輸出
    print(result.stdout)
    if result.stderr:
        print(f"Error: {result.stderr}")

print(f"timerange: --timerange='{timerange}'")
