version: '3'
services:
    app-front:
        image: node:18
        volumes:
            - '.:/app'
        tty: true
        working_dir: /app
        ports:
            - '${APP_FRONT_PORT:-8087}:${APP_FRONT_PORT:-8087}'
#        command: sh -c "npm run dev -- --host 0.0.0.0"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-8080}:8000'
        volumes:
            - '.:/app'
        depends_on:
            - mysql
            - redis
            - mongo
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_DOCKER_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: Asia/Taipei
        volumes:
          - mysql_data:/var/lib/mysql
    redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_FORWARD_PORT:-6379}:6379'
        volumes:
            - redis_data:/data
    mongo:
        image: 'mongo:6.0.4'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${DB_MONGO_USERNAME:-root}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_MONGO_PASSWORD:-root}'
        ports:
            - '${MONGO_DOCKER_PORT:-27017}:27017'
        volumes:
            - mongo_data:/data/db
volumes:
    mysql_data:
    redis_data:
    mongo_data:

